#!/usr/bin/env bash
#doing GOd works in his terbanacle

handle_sigterm() {
    echo "I hate the kill command"
    rm /var/run/myscript.pid
    exit 0
}


handle_sigint() {
    echo "Y U no love me?!"
}


handle_sigquit() {
    echo "Deleting PID file and terminating script."
    rm /var/run/myscript.pid
    exit 0
}

trap 'handle_sigterm' SIGTERM
trap 'handle_sigint' SIGINT
trap 'handle_sigquit' SIGQUIT


echo $$ > /var/run/myscript.pid

display_message() {
    while true; do
        echo "To infinity and beyond"
        sleep 2
    done
}

display_message
