#!/usr/bin/env bash
# bash script print to infinity and beyound 

sigterm_handler() {
    echo "I am invincible!!!"
    exit 0
}

display_message() {
trap 'sigterm_handler' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
}

display_message
