#!/usr/bin/env bash
# changing my home ip

if grep -q docker /proc/1/cgroup; then
    echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null
    echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
    echo "Hosts file updated successfully."
else
    echo "This script should be run inside a Docker container."
    exit 1
fi
